/**
 * @file
 * Testing functionality.
 *
 * Provides functions to generate "random" data to test Tripal D3 charts. Due
 * to the application no effort was made to chose the "best" random algorithms. ;-p
 */
tripalD3.test = {

  /**
   * Generate a single-series label/count dataset.
   *
   * Suitable for use with simplepie, simpledonut, simplebar
   */
  'randomSingleSeries': function(number, maxCount, minCount) {

    // Set some defaults.
    number = number || 5;
    maxCount = maxCount || 10000;
    minCount = minCount || 500;

    // get random labels for each member of the dataset.
    var labels = tripalD3.test.randomLabels(number);

    // Now generate the dataset.
    var dataset = [];
    labels.forEach(function(label) {
      var count = Math.floor(Math.random() * (maxCount - minCount)) + minCount;
      dataset.push({
        'label': label,
        'count': count,
      });
    });

    return dataset;
  },

  /**
   * Generate random words to be used as labels. All labels consist of two parts
   * to test that your chart correctly handles spaces.
   *
   * @param number
   *   The number of labels you want returned. Maximum of 200.
   *
   * @return
   *   An array containing the number of labels you requested.
   */
  'randomLabels' : function(number) {

    // The list of possible labels.
    // Possible labels were generated by http://www.fantasynamegenerators.com/latin-names.php
    // with a bias towards female names.
    var allLabels = [
      'Demaenetus Cassius', 'Pseudolus Opis', 'Franciscus Longinus', 'Peniculus Tiberinus',
      'Stalagmus Sisenna', 'Adulescens Ripanus', 'Philoxenus Terenteius', 'Cario Britannicus',
      'Philolaches Seneca', 'Hegio Gaius', 'Bruttia Constans', 'Cloelia Tranio', 'Caecia Volturcius',
      'Vassenia Rutilius', 'Cosconia Camerarius', 'Duronia Abercius', 'Stertinia Sellic',
      'Antistia Lartius', 'Aburia Tutor', 'Modia Ignatius', 'Milphidippa Mico', 'Maelia Lucanus',
      'Didia Vergilius', 'Spuria Arcadius', 'Suedia Papinian', 'Rutilia Frumentius', 'Pomponia Herculius',
      'Titiedia Hilaris', 'Ampelisca Ventor', 'Duccia Viator', 'Nemetoria Trupo', 'Cocceia Maius',
      'Rufria Frugius', 'Sennia Opilio', 'Rusonia Fidelis', 'Secundia Sebastius', 'Minicia Rector',
      'Bucculeia Constans', 'Cluilia Cremutius', 'Caepasia Caldus', 'Carvilia Cencius', 'Aquillia Bonus',
      'Caedicia Naso', 'Faenia Martius', 'Attia Senecio', 'Cocceia Publicus', 'Otacilia Ambrosius',
      'Urgulania Dalmatius', 'Fulcinia Valens', 'Gratidia Firmus', 'Caedicia Papus', 'Bantia Auspex',
      'Septia Tarquinius', 'Peltrasia Maursus', 'Rutilia Nazarius', 'Vipstana Scipio', 'Mallia Turpilius',
      'Viridia Carnifex', 'Artoria Albani', 'Minicia Tiberinus', 'Canuleia Florens', 'Metilia Fronto',
      'Curtia Italicus', 'Liburnia Luccius', 'Annia Vitus', 'Cantilia Burcanius', 'Plautia Naevius',
      'Seia Hortensius', 'Cocceia Fabius', 'Augustina Sisinnius', 'Lucia Afer', 'Sornatia Vettonius',
      'Angela Congrio', 'Calventia Fadus', 'Tertinia Figulus', 'Dillia Leon', 'Sestia Lucius',
      'Vitruvia Pacatius', 'Curia Minicius', 'Papiria Pomponius', 'Julia Pratensis', 'Caeparia Plautus',
      'Babudia Geminius', 'Grania Tertulus', 'Fufia Marcallas', 'Norbana Sudrenus', 'Caesonia Lupercus',
      'Tertinia Surinus', 'Aquillia Trogus', 'Lafrenia Carbo', 'Festinia Iavolenus', 'Pontia Claudius',
      'Cominia Symphorian', 'Lucceia Novellius', 'Baebia Tertius', 'Epidia Licinius', 'Vassenia Lucan',
      'Manlia Nabor', 'Vibidia Marcellinus', 'Munia Novation', 'Caepasia Sisenna', 'Quinctia Metunus',
      'Volusia Gratian', 'Allectia Eumenius', 'Titiedia Zeno', 'Artoria Meminius', 'Titinia Hermina',
      'Bruttia Palicamus', 'Murria Latinius', 'Pompilia Sura', 'Dionysia Osterius', 'Cominia Elvorix',
      'Lucretia Iavolenus', 'Pontidia Sisinnius', 'Cluntia Curio', 'Urgulania Super', 'Dillia Lupinus',
      'Floridia Superbus', 'Floronia Ulixes', 'Hortensia Alethius', 'Icilia Quintilius', 'Baebia Crispian',
      'Vatinia Tullius', 'Calpurnia Bonifatius', 'Labiena Fimbria', 'Festinia Asina', 'Canidia Mercurialis',
      'Aquillia Telesinus', 'Petellia Typhoeus', 'Papinia Siricus', 'Papia Genesius', 'Septia Carnifex',
      'Ummidia Verus', 'Faleria Tremellius', 'Sidonia Sylvius', 'Albatia Pulcherius', 'Maximia Pachomius',
      'Juventia Habitus', 'Sallustia Sacerdos', 'Arria Hesychius', 'Sentia Verrucosis', 'Amatia Scato',
      'Ampelisca Panaetius', 'Caecia Catius', 'Tremellia Valerian', 'Floronia Zosimus', 'Gratidia Rufinius',
      'Papia Maximian', 'Placidia Dubitatius', 'Secundia Sympronian', 'Uulia Porphyrius', 'Duronia Pacatius',
      'Volusena Sentius', 'Manilia Musicus', 'Opsia Scaevola', 'Hirtia Scribonius', 'Sempronia Gryllus',
      'Atria Pelagius', 'Atronia Peregrinus', 'Herennia Laurentius', 'Alcesimus Nabor', 'Ludovicus Capiton',
      'Pius Messala', 'Turbalio Galenus', 'Henricus Fortunatus', 'Lyco Balduinus', 'Peniculus Pudentius',
      'Lystiteles Tertullian', 'Periplectomenus Frigidian', 'Gallicles Limetanus', 'Sceledrus Romulius',
      'Dordalus Tiburtius', 'Cario Eutherius', 'Dinia Christius', 'Cleareta Symmachus', 'Sphaerio Ulfila',
      'Adulescens Ennodius', 'Artamo Typhoeus', 'Lorarii Fuscus', 'Chrysalus Ancus', 'Aristophontes Iustinius',
      'Petrus Paratus', 'Philoxenus Papinian', 'Milphio Zeno', 'Delphium Perperna', 'Sparax Victricius',
      'Philto Evodius', 'Sceledrus Vedrix', 'Cyamus Regulus', 'Lyco Toutius', 'Stadius Pantensus',
      'Sergius Verullus', 'Philocomasium Spendius', 'Augustinus Allectus', 'Demaenetus Musa',
      'Advocati Censorinus', 'Cario Eugenus', 'Ballio Venantius', 'Lena Tibullus', 'Crocotium Gallio'
    ];

    // First we sort the labels randomly...
    allLabels.sort(function() {return 0.5 - Math.random()});

    // We only support a max of 200 random labels...
    if (number > 200) {
      console.warn("TripalD3 random label generator only supports at most 200 random labels.") ;
      return allLabels;
    }
    else {
      // Return the number of labels we need.
      return allLabels.slice(0, number);
    }
  },
}