<?php

require_once('includes/stock_pedigree.inc');

/**
 * Implements hook_menu().
 */
function tripald3_menu() {
  $items = array();

  $items['ajax/tripal/d3-json/relationships/%/%'] = array(
    'title' => 'JS Graph: Tree',
    'page callback' => 'tripald3_get_relationship_json',
    'page arguments' => array(4,5),
    'access arguments' => array('view tripald3 json'),
    'type' => MENU_CALLBACK
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function tripald3_theme($existing, $type, $theme, $path) {
  $items = array();

  $items['tripald3_stock_pedigree'] = array(
    'template' => 'tripal_stock_pedigree',
    'path' => $path.'/templates',
    'variables' => array('node' => NULL),
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function tripald3_permission() {
  return array(
    'view tripald3 json' => array(
      'title' => t('View Tripal D3 JSON'),
      'description' => t('Required for anyone wanting to view a Tripal D3 diagram.'),
    ),
    'view tripald3 pedigree' => array(
      'title' => t('View Tripal D3 Pedigree'),
      'description' => t('Required to view the pedigree pane on stock pages.'),
    ),
  );
}

/**
 * Implements hook_node_view(). Acts on all content types.
 */
function tripald3_node_view($node, $view_mode, $langcode) {

  switch ($node->type) {
    case 'tripal_germplasm':
      if ($view_mode == 'full') {
        if(user_access('view tripald3 pedigree')) {

          // Only add the pedigree if there is more than the root node.
          if (!tripald3_is_node_leafless_tree($node->stock->stock_id)) {
            $node->content['tripal_stock_pedigree'] = array(
              '#theme' => 'tripald3_stock_pedigree',
              '#node' => $node,
              '#tripal_toc_id'    => 'pedigree',
              '#tripal_toc_title' => 'Pedigree'
            );
          }
        }
      }
    break;
  }
}
