<?php

// Include colour scheme api of this module.
// @see /api
module_load_include('inc', 'tripald3', 'api/color_scheme');

// Include pedigree api of this module.
// @see /api
module_load_include('inc', 'tripald3', 'api/pedigree');


/**
 * Implements hook_theme().
 * Used by Tripal D3 Integration Demo and Test pages.
 *
 * @see templates in /templates
 */
function tripald3_theme($existing, $type, $theme, $path) {  
  $variables = [
    // Tripal D3 Demo page theme.
    'theme_tripald3demo' => [
      'variables' => [],
      'template' => 'template-tripald3-demo',
    ],
    
    // Tripal D3 Test page theme.
    'theme_tripald3test' => [
      'variables' => [],
      'template' => 'template-tripald3-test',
    ]
  ];

  return $variables;
}